// The drift guard. Runs from the `eleventy.after` hook in .eleventy.js, reads
// the built site back off disk, and throws — failing `npm run build`, and with
// it PR CI — if the route registry, the rendered pages, the sitemap and the
// redirect stubs do not agree.
//
// This exists because SEO breakage is silent. A canonical link that says /bio
// where the sitemap says /bio/, a page added to the nav but never to the
// sitemap, a share image that stops being 1200x630 — none of it throws, none of
// it looks wrong in a browser, and all of it is invisible until rankings move
// months later. The checks below are deliberately about *agreement between
// artefacts* rather than the presence of individual tags: a missing tag is
// obvious in review, whereas two files that each look fine and contradict each
// other is not.
//
// It reads the output rather than the data it was generated from, on purpose.
// Asserting over src/_data/routes.js would only prove the data file agrees with
// itself; what has to hold is that what actually shipped agrees.

const fs = require("node:fs");
const path = require("node:path");

const site = require("../src/_data/site.json");
const routes = require("../src/_data/routes.js");

// Files that are legitimately not routes: they must not appear in the sitemap,
// and the per-route title/description rules do not apply to them.
const NON_ROUTE_OUTPUTS = new Set(["404.html"]);

class SeoAssertionError extends Error {}

function collectHtmlFiles(dir, base = dir, found = []) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) collectHtmlFiles(full, base, found);
        else if (entry.isFile() && entry.name.endsWith(".html")) {
            found.push({ absolute: full, relative: path.relative(base, full) });
        }
    }
    return found;
}

// The file Eleventy writes for a canonical path. "/" is index.html at the root;
// every other route is a directory URL, so /bio/ is bio/index.html.
function outputFileFor(outputDir, routePath) {
    return path.join(outputDir, routePath === "/" ? "index.html" : `${routePath}index.html`);
}

function read(file) {
    return fs.readFileSync(file, "utf8");
}

function attr(html, pattern) {
    const match = html.match(pattern);
    return match ? match[1] : null;
}

// Deliberately not an XML parser. The sitemap this reads is generated by a
// template a few lines long, and a hand-rolled match keeps the check honest:
// a lenient parser that silently tolerated a malformed document would defeat
// the point of checking the built file at all.
function sitemapLocs(xml) {
    return [...xml.matchAll(/<loc>([^<]*)<\/loc>/g)].map((m) => m[1]);
}

function assertSitemapMatchesRoutes(outputDir, problems) {
    const sitemapPath = path.join(outputDir, "sitemap.xml");
    if (!fs.existsSync(sitemapPath)) {
        problems.push("sitemap.xml was not generated");
        return;
    }

    const xml = read(sitemapPath);
    const found = sitemapLocs(xml);
    const expected = routes.sitemap.map((r) => `${site.origin}${r.path}`);

    const duplicates = found.filter((loc, i) => found.indexOf(loc) !== i);
    if (duplicates.length > 0) {
        problems.push(`sitemap.xml lists these URLs more than once: ${duplicates.join(", ")}`);
    }

    // Set comparison, reported as two directed differences, because "the
    // sitemap has an extra URL" and "the sitemap is missing one" are different
    // bugs with different fixes and a plain inequality message hides which.
    const missing = expected.filter((loc) => !found.includes(loc));
    const extra = found.filter((loc) => !expected.includes(loc));
    if (missing.length > 0) {
        problems.push(
            `sitemap.xml is missing ${missing.join(", ")} — every route in ` +
                `src/_data/routes.js must appear in it`,
        );
    }
    if (extra.length > 0) {
        problems.push(
            `sitemap.xml lists ${extra.join(", ")}, which is not a route in ` +
                `src/_data/routes.js — redirect stubs and /404.html must never be listed`,
        );
    }

    for (const loc of found) {
        if (!loc.startsWith(`${site.origin}/`)) {
            problems.push(`sitemap.xml entry "${loc}" is not an absolute URL under ${site.origin}`);
        }
    }
}

function assertRoutePages(outputDir, problems) {
    const titles = new Map();

    for (const route of routes.all) {
        const file = outputFileFor(outputDir, route.path);
        if (!fs.existsSync(file)) {
            problems.push(
                `route ${route.key} declares path ${route.path} but ` +
                    `${path.relative(outputDir, file)} was not written — the permalink in ` +
                    `src/${route.key === "home" ? "index" : route.key}.njk and the registry disagree`,
            );
            continue;
        }

        const html = read(file);
        const expectedUrl = `${site.origin}${route.path}`;

        const canonical = attr(html, /<link rel="canonical" href="([^"]*)"/);
        if (canonical !== expectedUrl) {
            problems.push(
                `${route.path} has canonical "${canonical}", expected "${expectedUrl}". ` +
                    `The canonical link, the sitemap and the redirect target must match ` +
                    `character for character, trailing slash included.`,
            );
        }

        const ogUrl = attr(html, /<meta property="og:url" content="([^"]*)"/);
        if (ogUrl !== expectedUrl) {
            problems.push(`${route.path} has og:url "${ogUrl}", expected "${expectedUrl}"`);
        }

        const title = attr(html, /<title>([^<]*)<\/title>/);
        if (!title) {
            problems.push(`${route.path} has an empty or missing title`);
        } else {
            if (titles.has(title)) {
                problems.push(
                    `${route.path} and ${titles.get(title)} share the title "${title}" — ` +
                        `every page needs a distinct one`,
                );
            }
            titles.set(title, route.path);
        }

        // A page still linking to a pre-flip URL would send visitors through a
        // meta-refresh hop on an internal click, which is exactly what the
        // stubs exist to avoid for *external* links only.
        for (const other of routes.redirects) {
            if (html.includes(`href="${other.legacy}"`)) {
                problems.push(
                    `${route.path} still links to the pre-flip URL ${other.legacy}; ` +
                        `internal links must use the canonical path ${other.path}`,
                );
            }
        }
    }
}

function assertRedirectStubs(outputDir, problems) {
    for (const route of routes.redirects) {
        const file = path.join(outputDir, route.legacy);
        if (!fs.existsSync(file)) {
            problems.push(
                `no redirect stub was written at ${route.legacy}. The URL flip and the ` +
                    `stubs are one change: shipping ${route.path} without ${route.legacy} ` +
                    `breaks every inbound link to the old URL.`,
            );
            continue;
        }

        const html = read(file);
        const canonical = attr(html, /<link rel="canonical" href="([^"]*)"/);
        if (canonical !== `${site.origin}${route.path}`) {
            problems.push(
                `${route.legacy} points its canonical at "${canonical}", ` +
                    `expected "${site.origin}${route.path}"`,
            );
        }

        const refresh = attr(html, /<meta http-equiv="refresh" content="([^"]*)"/);
        if (refresh !== `0; url=${route.path}`) {
            problems.push(
                `${route.legacy} has refresh "${refresh}", expected "0; url=${route.path}"`,
            );
        }

        // The visible fallback is what a visitor gets if their browser or
        // extension ignores the refresh. Without it the stub is a blank page.
        if (!html.includes(`href="${route.path}"`)) {
            problems.push(`${route.legacy} has no visible fallback link to ${route.path}`);
        }
    }
}

function assertNoEmptyMetadata(outputDir, problems) {
    for (const { absolute, relative } of collectHtmlFiles(outputDir)) {
        const html = read(absolute);

        // The original failure this ticket was filed over: og:title, og:url,
        // og:image and og:description all shipped as content="" on all six
        // pages. Checking the built HTML catches it wherever it comes from.
        if (html.includes('content=""')) {
            problems.push(`${relative} still contains an empty content="" attribute`);
        }
        // An empty href resolves to the current document, so every page load
        // re-fetches its own HTML as an icon.
        if (html.includes('href=""')) {
            problems.push(
                `${relative} contains an empty href="", which resolves to the page itself`,
            );
        }
        if (!/<title>[^<]+<\/title>/.test(html)) {
            problems.push(`${relative} has no non-empty title`);
        }
        if (!/<link rel="canonical" href="https?:[^"]+"/.test(html)) {
            problems.push(`${relative} has no absolute canonical link`);
        }
        if (!NON_ROUTE_OUTPUTS.has(relative) && !/<html lang="[^"]+"/.test(html)) {
            problems.push(`${relative} has no lang attribute on the html element`);
        }
    }
}

function assertRobots(outputDir, problems) {
    const file = path.join(outputDir, "robots.txt");
    if (!fs.existsSync(file)) {
        problems.push("robots.txt was not generated");
        return;
    }
    const text = read(file);
    const expected = `Sitemap: ${site.origin}/sitemap.xml`;
    if (!text.includes(expected)) {
        problems.push(`robots.txt does not contain "${expected}"`);
    }
    if (!/^User-agent:\s*\*$/m.test(text)) {
        problems.push("robots.txt has no `User-agent: *` group");
    }
}

// The share image is the one asset whose *dimensions* are a published promise:
// site.json declares og:image:width and og:image:height, and scrapers lay the
// card out from those numbers before fetching the file. Measuring the built
// file is what stops the declaration and the artefact drifting apart.
async function assertBrandAssets(outputDir, problems) {
    for (const name of ["favicon.ico", "favicon.svg", "apple-touch-icon.png"]) {
        if (!fs.existsSync(path.join(outputDir, name))) {
            problems.push(`${name} was not written — the icon links in base.njk would 404`);
        }
    }

    const ogPath = path.join(outputDir, site.ogImage.path);
    if (!fs.existsSync(ogPath)) {
        problems.push(`the share image ${site.ogImage.path} was not written`);
        return;
    }

    const sharp = require("sharp");
    const meta = await sharp(ogPath).metadata();
    if (meta.width !== site.ogImage.width || meta.height !== site.ogImage.height) {
        problems.push(
            `${site.ogImage.path} is ${meta.width}x${meta.height} but site.json declares ` +
                `${site.ogImage.width}x${site.ogImage.height} in og:image:width/height`,
        );
    }
}

module.exports = async function assertSeo(outputDir) {
    if (!fs.existsSync(outputDir)) {
        throw new SeoAssertionError(`assert-seo: no build output at ${outputDir}`);
    }

    // Every check appends to one list rather than throwing on the first
    // failure, so a build reports all the drift at once instead of making the
    // author rebuild to discover the next problem.
    const problems = [];
    assertSitemapMatchesRoutes(outputDir, problems);
    assertRoutePages(outputDir, problems);
    assertRedirectStubs(outputDir, problems);
    assertNoEmptyMetadata(outputDir, problems);
    assertRobots(outputDir, problems);
    await assertBrandAssets(outputDir, problems);

    if (problems.length > 0) {
        throw new SeoAssertionError(
            `SEO assertions failed (${problems.length}):\n` +
                problems.map((p) => `  - ${p}`).join("\n") +
                `\n\nThese compare the built site against the route registry in ` +
                `src/_data/routes.js. Fix the registry or the template it disagrees with; ` +
                `do not relax the check.`,
        );
    }

    console.log(
        `assert-seo  ${routes.all.length} routes, ${routes.redirects.length} redirect stubs, ` +
            `sitemap and canonicals agree`,
    );
};
